[project]
name = "nolanlab-dlc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "tables>=3.10.2",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
]
